const GeoLayout _002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(1, _002_switch_optionhead__no_cap__mesh_mat_override_face_1__1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout _002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(1, _002_switch_optionhead__no_cap__mesh_mat_override_face_2_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout _002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(1, _002_switch_optionhead__no_cap__mesh_mat_override_face_2_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout _002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(1, _002_switch_optionhead__no_cap__mesh_mat_override_face_2_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout _002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(1, _002_switch_optionhead__no_cap__mesh_mat_override_face_2_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout _002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(1, _002_switch_optionhead__no_cap__mesh_mat_override_face_2_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout _002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt7[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(1, _002_switch_optionhead__no_cap__mesh_mat_override_face_7_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout armature_002_switch_option_002[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(1, _002_switch_optionhead__no_cap__mesh),
			GEO_CLOSE_NODE(),
			GEO_BRANCH(1, _002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt1),
			GEO_BRANCH(1, _002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt2),
			GEO_BRANCH(1, _002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt3),
			GEO_BRANCH(1, _002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt4),
			GEO_BRANCH(1, _002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt5),
			GEO_BRANCH(1, _002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt6),
			GEO_BRANCH(1, _002_switch_opt0_001_switch_opt0_000_switch_opt1_switch_face_opt7),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout right_hand_open_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(1, 89, 0, 0, _002_switch_optionright_hand_open_mesh),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout left_hand_open_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(1, 89, 0, 0, _002_switch_optionleft_hand_open_mesh),
		GEO_OPEN_NODE(),
			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout left_hand_peace_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(1, 89, 0, 0, _004_switch_optionleft_hand_peace_mesh),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout left_hand_cap_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(1, 89, 0, 0, _005_switch_optionleft_hand_cap_mesh),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout left_hand_wing_cap_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(1, 89, 0, 0, _006_switch_optionleft_hand_wing_cap_mesh),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(4, _006_switch_optionleft_hand_wing_cap_wings_mesh),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout _002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(5, _002_switch_optionhead__no_cap__mesh_mat_override_face_1__1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout _002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(5, _002_switch_optionhead__no_cap__mesh_mat_override_face_2_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout _002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(5, _002_switch_optionhead__no_cap__mesh_mat_override_face_2_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout _002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(5, _002_switch_optionhead__no_cap__mesh_mat_override_face_2_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout _002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(5, _002_switch_optionhead__no_cap__mesh_mat_override_face_2_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout _002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(5, _002_switch_optionhead__no_cap__mesh_mat_override_face_2_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout _002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt7[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(5, _002_switch_optionhead__no_cap__mesh_mat_override_face_7_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout _002_switch_opt0_001_switch_opt1_jump_armature_002_switch_option_002[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(5, _002_switch_optionhead__no_cap__mesh),
			GEO_CLOSE_NODE(),
			GEO_BRANCH(1, _002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt1),
			GEO_BRANCH(1, _002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt2),
			GEO_BRANCH(1, _002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt3),
			GEO_BRANCH(1, _002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt4),
			GEO_BRANCH(1, _002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt5),
			GEO_BRANCH(1, _002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt6),
			GEO_BRANCH(1, _002_switch_opt0_001_switch_opt1_000_switch_opt1_switch_face_opt7),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout _002_switch_opt0_001_switch_opt1_jump_right_hand_open_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(5, 89, 0, 0, _002_switch_optionright_hand_open_mesh),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout _002_switch_opt0_001_switch_opt1_jump_left_hand_open_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(5, 89, 0, 0, _002_switch_optionleft_hand_open_mesh),
		GEO_OPEN_NODE(),
			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout _002_switch_opt0_001_switch_opt1_jump_left_hand_peace_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(5, 89, 0, 0, _004_switch_optionleft_hand_peace_mesh),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout _002_switch_opt0_001_switch_opt1_jump_left_hand_cap_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(5, 89, 0, 0, _005_switch_optionleft_hand_cap_mesh),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout _002_switch_opt0_001_switch_opt1_jump_left_hand_wing_cap_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(5, 89, 0, 0, _006_switch_optionleft_hand_wing_cap_mesh),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(5, _006_switch_optionleft_hand_wing_cap_wings_mesh),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout _002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(5, _000_displaylist_mesh_mat_override_face_1__1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout _002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(5, _000_displaylist_mesh_mat_override_face_2_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout _002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(5, _000_displaylist_mesh_mat_override_face_2_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout _002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(5, _000_displaylist_mesh_mat_override_face_2_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout _002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(5, _000_displaylist_mesh_mat_override_face_2_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout _002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(5, _000_displaylist_mesh_mat_override_face_2_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout _002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt7[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(5, _000_displaylist_mesh_mat_override_face_7_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout _002_switch_opt0_001_switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(1, 0, 367, -1, NULL),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(5, 0, 0, 0, _000_offset_mesh),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(5, _000_offset_001_skinned),
				GEO_ASM(0, Geo18_802B1BB0),
				GEO_ASM(0, Geo18_80277294),
				GEO_ROTATION_NODE(0, 0, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(5, 66, 22, 0, _000_offset_001_mesh),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(1, 161, -16, 0, NULL),
						GEO_OPEN_NODE(),
							GEO_ASM(0, Geo18_802773A4),
							GEO_ROTATION_NODE(0, 0, 0, 0),
							GEO_OPEN_NODE(),
								GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
								GEO_OPEN_NODE(),
									GEO_NODE_START(),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(5, _000_displaylist_mesh),
											GEO_CLOSE_NODE(),
											GEO_BRANCH(1, _002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt1),
											GEO_BRANCH(1, _002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt2),
											GEO_BRANCH(1, _002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt3),
											GEO_BRANCH(1, _002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt4),
											GEO_BRANCH(1, _002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt5),
											GEO_BRANCH(1, _002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt6),
											GEO_BRANCH(1, _002_switch_opt0_001_switch_opt1_000_switch_opt0_000_switch_001_opt7),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_BRANCH(1, _002_switch_opt0_001_switch_opt1_jump_armature_002_switch_option_002),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(0, 61, -34, -122, 15, -33, -133),
								GEO_OPEN_NODE(),
									GEO_ASM(0, Geo18_80277824),
									GEO_ROTATION_NODE(0, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(5, _000_displaylist_001_mesh),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(0, 61, -34, 122, -15, 33, -133),
								GEO_OPEN_NODE(),
									GEO_ASM(1, Geo18_80277824),
									GEO_ROTATION_NODE(0, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(5, _000_displaylist_002_mesh),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_DISPLAY_LIST(5, _000_offset_003_skinned),
						GEO_TRANSLATE_ROTATE(1, 96, -28, 77, 0, 0, -5),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_TRANSLATE_ROTATE(1, 0, 0, 0, 0, 0, 5),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(5, 0, 0, 0, _000_offset_003_mesh),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(5, _000_offset_004_skinned),
										GEO_ANIMATED_PART(5, 121, -11, 0, _000_offset_004_mesh),
										GEO_OPEN_NODE(),
											GEO_SWITCH_CASE(1, geo_switch_mario_hand),
											GEO_OPEN_NODE(),
												GEO_NODE_START(),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(1, 113, 0, 0, NULL),
													GEO_OPEN_NODE(),
														GEO_ASM(1, Geo18_802775CC),
														GEO_SCALE(0, 65536),
														GEO_OPEN_NODE(),
															GEO_DISPLAY_LIST(5, _000_displaylist_003_mesh),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
												GEO_BRANCH(1, _002_switch_opt0_001_switch_opt1_jump_right_hand_open_armature),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_DISPLAY_LIST(5, _000_offset_006_skinned),
						GEO_ANIMATED_PART(1, 95, -28, -77, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(5, 0, 0, 0, _000_offset_006_mesh),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(5, _000_offset_007_skinned),
								GEO_TRANSLATE_ROTATE(1, 115, -11, 0, 0, 0, 0),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(5, 0, 0, 0, _000_offset_007_mesh),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(0, geo_switch_mario_hand),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(1, 121, 0, 0, NULL),
												GEO_OPEN_NODE(),
													GEO_ASM(0, Geo18_802775CC),
													GEO_SCALE(0, 65536),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(5, _000_displaylist_004_mesh),
													GEO_CLOSE_NODE(),
													GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
											GEO_BRANCH(1, _002_switch_opt0_001_switch_opt1_jump_left_hand_open_armature),
											GEO_BRANCH(1, _002_switch_opt0_001_switch_opt1_jump_left_hand_peace_armature),
											GEO_BRANCH(1, _002_switch_opt0_001_switch_opt1_jump_left_hand_cap_armature),
											GEO_BRANCH(1, _002_switch_opt0_001_switch_opt1_jump_left_hand_wing_cap_armature),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_DISPLAY_LIST(5, _000_offset_009_skinned),
				GEO_ANIMATED_PART(1, -83, 11, 41, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(5, 0, 0, 0, _000_offset_009_mesh),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(5, _000_offset_010_skinned),
						GEO_ANIMATED_PART(5, 196, -17, -6, _000_offset_010_mesh),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(5, _000_offset_011_skinned),
							GEO_ANIMATED_PART(5, 228, 36, 0, _000_offset_011_mesh),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_DISPLAY_LIST(5, _000_offset_012_skinned),
				GEO_ANIMATED_PART(1, -83, 11, -41, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(5, 0, 0, 0, _000_offset_012_mesh),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(5, _000_offset_013_skinned),
						GEO_ANIMATED_PART(5, 196, -17, 9, _000_offset_013_mesh),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(5, _000_displaylist_005_skinned),
							GEO_ANIMATED_PART(1, 228, 36, -15, NULL),
							GEO_OPEN_NODE(),
								GEO_ASM(2, Geo18_802775CC),
								GEO_SCALE(0, 65536),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(5, _000_displaylist_005_mesh),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout _002_switch_opt0_001_switch_opt2_jump_armature_002_switch_option_002[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(1, _002_switch_optionhead__no_cap__mesh_mat_override_metal_0),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout _002_switch_opt0_001_switch_opt2_jump_right_hand_open_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(1, 89, 0, 0, _002_switch_optionright_hand_open_mesh_mat_override_metal_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout _002_switch_opt0_001_switch_opt2_jump_left_hand_open_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(1, 89, 0, 0, _002_switch_optionleft_hand_open_mesh_mat_override_metal_0),
		GEO_OPEN_NODE(),
			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout _002_switch_opt0_001_switch_opt2_jump_left_hand_peace_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(1, 89, 0, 0, _004_switch_optionleft_hand_peace_mesh_mat_override_metal_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout _002_switch_opt0_001_switch_opt2_jump_left_hand_cap_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(1, 89, 0, 0, _005_switch_optionleft_hand_cap_mesh_mat_override_metal_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout _002_switch_opt0_001_switch_opt2_jump_left_hand_wing_cap_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(1, 89, 0, 0, _006_switch_optionleft_hand_wing_cap_mesh_mat_override_metal_0),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(4, _006_switch_optionleft_hand_wing_cap_wings_mesh_mat_override_metal_0),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout _002_switch_opt0_001_switch_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(1, 0, 367, -1, NULL),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(1, 0, 0, 0, _000_offset_mesh_mat_override_metal_0),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(1, _000_offset_001_skinned_mat_override_metal_0),
				GEO_ASM(0, Geo18_802B1BB0),
				GEO_ASM(0, Geo18_80277294),
				GEO_ROTATION_NODE(0, 0, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(1, 66, 22, 0, _000_offset_001_mesh_mat_override_metal_0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(1, 161, -16, 0, NULL),
						GEO_OPEN_NODE(),
							GEO_ASM(0, Geo18_802773A4),
							GEO_ROTATION_NODE(0, 0, 0, 0),
							GEO_OPEN_NODE(),
								GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
								GEO_OPEN_NODE(),
									GEO_NODE_START(),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(1, _000_displaylist_mesh_mat_override_metal_0),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_BRANCH(1, _002_switch_opt0_001_switch_opt2_jump_armature_002_switch_option_002),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(0, 61, -34, -122, 15, -33, -133),
								GEO_OPEN_NODE(),
									GEO_ASM(0, Geo18_80277824),
									GEO_ROTATION_NODE(0, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(4, _000_displaylist_001_mesh_mat_override_metal_0),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(0, 61, -34, 122, -15, 33, -133),
								GEO_OPEN_NODE(),
									GEO_ASM(1, Geo18_80277824),
									GEO_ROTATION_NODE(0, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(4, _000_displaylist_002_mesh_mat_override_metal_0),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_DISPLAY_LIST(1, _000_offset_003_skinned_mat_override_metal_0),
						GEO_TRANSLATE_ROTATE(1, 96, -28, 77, 0, 0, -5),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_TRANSLATE_ROTATE(1, 0, 0, 0, 0, 0, 5),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(1, 0, 0, 0, _000_offset_003_mesh_mat_override_metal_0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(1, _000_offset_004_skinned_mat_override_metal_0),
										GEO_ANIMATED_PART(1, 121, -11, 0, _000_offset_004_mesh_mat_override_metal_0),
										GEO_OPEN_NODE(),
											GEO_SWITCH_CASE(1, geo_switch_mario_hand),
											GEO_OPEN_NODE(),
												GEO_NODE_START(),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(1, 113, 0, 0, NULL),
													GEO_OPEN_NODE(),
														GEO_ASM(1, Geo18_802775CC),
														GEO_SCALE(0, 65536),
														GEO_OPEN_NODE(),
															GEO_DISPLAY_LIST(1, _000_displaylist_003_mesh_mat_override_metal_0),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
												GEO_BRANCH(1, _002_switch_opt0_001_switch_opt2_jump_right_hand_open_armature),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_DISPLAY_LIST(1, _000_offset_006_skinned_mat_override_metal_0),
						GEO_ANIMATED_PART(1, 95, -28, -77, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(1, 0, 0, 0, _000_offset_006_mesh_mat_override_metal_0),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(1, _000_offset_007_skinned_mat_override_metal_0),
								GEO_TRANSLATE_ROTATE(1, 115, -11, 0, 0, 0, 0),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(1, 0, 0, 0, _000_offset_007_mesh_mat_override_metal_0),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(0, geo_switch_mario_hand),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(1, 121, 0, 0, NULL),
												GEO_OPEN_NODE(),
													GEO_ASM(0, Geo18_802775CC),
													GEO_SCALE(0, 65536),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(1, _000_displaylist_004_mesh_mat_override_metal_0),
													GEO_CLOSE_NODE(),
													GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
											GEO_BRANCH(1, _002_switch_opt0_001_switch_opt2_jump_left_hand_open_armature),
											GEO_BRANCH(1, _002_switch_opt0_001_switch_opt2_jump_left_hand_peace_armature),
											GEO_BRANCH(1, _002_switch_opt0_001_switch_opt2_jump_left_hand_cap_armature),
											GEO_BRANCH(1, _002_switch_opt0_001_switch_opt2_jump_left_hand_wing_cap_armature),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_DISPLAY_LIST(1, _000_offset_009_skinned_mat_override_metal_0),
				GEO_ANIMATED_PART(1, -83, 11, 41, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(1, 0, 0, 0, _000_offset_009_mesh_mat_override_metal_0),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(1, _000_offset_010_skinned_mat_override_metal_0),
						GEO_ANIMATED_PART(1, 196, -17, -6, _000_offset_010_mesh_mat_override_metal_0),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(1, _000_offset_011_skinned_mat_override_metal_0),
							GEO_ANIMATED_PART(1, 228, 36, 0, _000_offset_011_mesh_mat_override_metal_0),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_DISPLAY_LIST(1, _000_offset_012_skinned_mat_override_metal_0),
				GEO_ANIMATED_PART(1, -83, 11, -41, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(1, 0, 0, 0, _000_offset_012_mesh_mat_override_metal_0),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(1, _000_offset_013_skinned_mat_override_metal_0),
						GEO_ANIMATED_PART(1, 196, -17, 9, _000_offset_013_mesh_mat_override_metal_0),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(1, _000_displaylist_005_skinned_mat_override_metal_0),
							GEO_ANIMATED_PART(1, 228, 36, -15, NULL),
							GEO_OPEN_NODE(),
								GEO_ASM(2, Geo18_802775CC),
								GEO_SCALE(0, 65536),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(1, _000_displaylist_005_mesh_mat_override_metal_0),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout _002_switch_opt0_001_switch_opt3_jump_armature_002_switch_option_002[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(5, _002_switch_optionhead__no_cap__mesh_mat_override_metal_0),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout _002_switch_opt0_001_switch_opt3_jump_right_hand_open_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(5, 89, 0, 0, _002_switch_optionright_hand_open_mesh_mat_override_metal_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout _002_switch_opt0_001_switch_opt3_jump_left_hand_open_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(5, 89, 0, 0, _002_switch_optionleft_hand_open_mesh_mat_override_metal_0),
		GEO_OPEN_NODE(),
			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout _002_switch_opt0_001_switch_opt3_jump_left_hand_peace_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(5, 89, 0, 0, _004_switch_optionleft_hand_peace_mesh_mat_override_metal_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout _002_switch_opt0_001_switch_opt3_jump_left_hand_cap_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(5, 89, 0, 0, _005_switch_optionleft_hand_cap_mesh_mat_override_metal_0),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout _002_switch_opt0_001_switch_opt3_jump_left_hand_wing_cap_armature[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(5, 89, 0, 0, _006_switch_optionleft_hand_wing_cap_mesh_mat_override_metal_0),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(5, _006_switch_optionleft_hand_wing_cap_wings_mesh_mat_override_metal_0),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout _002_switch_opt0_001_switch_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(1, 0, 367, -1, NULL),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(5, 0, 0, 0, _000_offset_mesh_mat_override_metal_0),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(5, _000_offset_001_skinned_mat_override_metal_0),
				GEO_ASM(0, Geo18_802B1BB0),
				GEO_ASM(0, Geo18_80277294),
				GEO_ROTATION_NODE(0, 0, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(5, 66, 22, 0, _000_offset_001_mesh_mat_override_metal_0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(1, 161, -16, 0, NULL),
						GEO_OPEN_NODE(),
							GEO_ASM(0, Geo18_802773A4),
							GEO_ROTATION_NODE(0, 0, 0, 0),
							GEO_OPEN_NODE(),
								GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
								GEO_OPEN_NODE(),
									GEO_NODE_START(),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(5, _000_displaylist_mesh_mat_override_metal_0),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_BRANCH(1, _002_switch_opt0_001_switch_opt3_jump_armature_002_switch_option_002),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(0, 61, -34, -122, 15, -33, -133),
								GEO_OPEN_NODE(),
									GEO_ASM(0, Geo18_80277824),
									GEO_ROTATION_NODE(0, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(5, _000_displaylist_001_mesh_mat_override_metal_0),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(0, 61, -34, 122, -15, 33, -133),
								GEO_OPEN_NODE(),
									GEO_ASM(1, Geo18_80277824),
									GEO_ROTATION_NODE(0, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(5, _000_displaylist_002_mesh_mat_override_metal_0),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_DISPLAY_LIST(5, _000_offset_003_skinned_mat_override_metal_0),
						GEO_TRANSLATE_ROTATE(1, 96, -28, 77, 0, 0, -5),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_TRANSLATE_ROTATE(1, 0, 0, 0, 0, 0, 5),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(5, 0, 0, 0, _000_offset_003_mesh_mat_override_metal_0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(5, _000_offset_004_skinned_mat_override_metal_0),
										GEO_ANIMATED_PART(5, 121, -11, 0, _000_offset_004_mesh_mat_override_metal_0),
										GEO_OPEN_NODE(),
											GEO_SWITCH_CASE(1, geo_switch_mario_hand),
											GEO_OPEN_NODE(),
												GEO_NODE_START(),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(1, 113, 0, 0, NULL),
													GEO_OPEN_NODE(),
														GEO_ASM(1, Geo18_802775CC),
														GEO_SCALE(0, 65536),
														GEO_OPEN_NODE(),
															GEO_DISPLAY_LIST(5, _000_displaylist_003_mesh_mat_override_metal_0),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
												GEO_BRANCH(1, _002_switch_opt0_001_switch_opt3_jump_right_hand_open_armature),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_DISPLAY_LIST(5, _000_offset_006_skinned_mat_override_metal_0),
						GEO_ANIMATED_PART(1, 95, -28, -77, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(5, 0, 0, 0, _000_offset_006_mesh_mat_override_metal_0),
							GEO_OPEN_NODE(),
								GEO_DISPLAY_LIST(5, _000_offset_007_skinned_mat_override_metal_0),
								GEO_TRANSLATE_ROTATE(1, 115, -11, 0, 0, 0, 0),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(5, 0, 0, 0, _000_offset_007_mesh_mat_override_metal_0),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(0, geo_switch_mario_hand),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(1, 121, 0, 0, NULL),
												GEO_OPEN_NODE(),
													GEO_ASM(0, Geo18_802775CC),
													GEO_SCALE(0, 65536),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(5, _000_displaylist_004_mesh_mat_override_metal_0),
													GEO_CLOSE_NODE(),
													GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
											GEO_BRANCH(1, _002_switch_opt0_001_switch_opt3_jump_left_hand_open_armature),
											GEO_BRANCH(1, _002_switch_opt0_001_switch_opt3_jump_left_hand_peace_armature),
											GEO_BRANCH(1, _002_switch_opt0_001_switch_opt3_jump_left_hand_cap_armature),
											GEO_BRANCH(1, _002_switch_opt0_001_switch_opt3_jump_left_hand_wing_cap_armature),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_DISPLAY_LIST(5, _000_offset_009_skinned_mat_override_metal_0),
				GEO_ANIMATED_PART(1, -83, 11, 41, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(5, 0, 0, 0, _000_offset_009_mesh_mat_override_metal_0),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(5, _000_offset_010_skinned_mat_override_metal_0),
						GEO_ANIMATED_PART(5, 196, -17, -6, _000_offset_010_mesh_mat_override_metal_0),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(5, _000_offset_011_skinned_mat_override_metal_0),
							GEO_ANIMATED_PART(5, 228, 36, 0, _000_offset_011_mesh_mat_override_metal_0),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_DISPLAY_LIST(5, _000_offset_012_skinned_mat_override_metal_0),
				GEO_ANIMATED_PART(1, -83, 11, -41, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(5, 0, 0, 0, _000_offset_012_mesh_mat_override_metal_0),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(5, _000_offset_013_skinned_mat_override_metal_0),
						GEO_ANIMATED_PART(5, 196, -17, 9, _000_offset_013_mesh_mat_override_metal_0),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(5, _000_displaylist_005_skinned_mat_override_metal_0),
							GEO_ANIMATED_PART(1, 228, 36, -15, NULL),
							GEO_OPEN_NODE(),
								GEO_ASM(2, Geo18_802775CC),
								GEO_SCALE(0, 65536),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(5, _000_displaylist_005_mesh_mat_override_metal_0),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout _002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(1, _000_displaylist_mesh_mat_override_face_1__1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout _002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(1, _000_displaylist_mesh_mat_override_face_2_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout _002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(1, _000_displaylist_mesh_mat_override_face_2_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout _002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(1, _000_displaylist_mesh_mat_override_face_2_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout _002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(1, _000_displaylist_mesh_mat_override_face_2_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout _002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(1, _000_displaylist_mesh_mat_override_face_2_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout _002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt7[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(1, _000_displaylist_mesh_mat_override_face_7_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout mario_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(1, 180, 100),
		GEO_OPEN_NODE(),
			GEO_SCALE(0, 16384),
			GEO_OPEN_NODE(),
				GEO_ASM(0, geo_mirror_mario_backface_culling),
				GEO_ASM(0, Geo18_802770A4),
				GEO_SWITCH_CASE(0, geo_switch_mario_stand_run),
				GEO_OPEN_NODE(),
					GEO_NODE_START(),
					GEO_OPEN_NODE(),
						GEO_SWITCH_CASE(0, geo_switch_mario_cap_effect),
						GEO_OPEN_NODE(),
							GEO_NODE_START(),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(1, 0, 367, -1, NULL),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(1, 0, 0, 0, _000_offset_mesh),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(1, _000_offset_001_skinned),
										GEO_ASM(0, Geo18_802B1BB0),
										GEO_ASM(0, Geo18_80277294),
										GEO_ROTATION_NODE(0, 0, 0, 0),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(1, 66, 22, 0, _000_offset_001_mesh),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(1, 161, -16, 0, NULL),
												GEO_OPEN_NODE(),
													GEO_ASM(0, Geo18_802773A4),
													GEO_ROTATION_NODE(0, 0, 0, 0),
													GEO_OPEN_NODE(),
														GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
														GEO_OPEN_NODE(),
															GEO_NODE_START(),
															GEO_OPEN_NODE(),
																GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
																GEO_OPEN_NODE(),
																	GEO_NODE_START(),
																	GEO_OPEN_NODE(),
																		GEO_DISPLAY_LIST(1, _000_displaylist_mesh),
																	GEO_CLOSE_NODE(),
																	GEO_BRANCH(1, _002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt1),
																	GEO_BRANCH(1, _002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt2),
																	GEO_BRANCH(1, _002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt3),
																	GEO_BRANCH(1, _002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt4),
																	GEO_BRANCH(1, _002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt5),
																	GEO_BRANCH(1, _002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt6),
																	GEO_BRANCH(1, _002_switch_opt0_001_switch_opt0_000_switch_opt0_000_switch_001_opt7),
																GEO_CLOSE_NODE(),
															GEO_CLOSE_NODE(),
															GEO_BRANCH(1, armature_002_switch_option_002),
														GEO_CLOSE_NODE(),
														GEO_TRANSLATE_ROTATE(0, 61, -34, -122, 15, -33, -133),
														GEO_OPEN_NODE(),
															GEO_ASM(0, Geo18_80277824),
															GEO_ROTATION_NODE(0, 0, 0, 0),
															GEO_OPEN_NODE(),
																GEO_DISPLAY_LIST(4, _000_displaylist_001_mesh),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
														GEO_TRANSLATE_ROTATE(0, 61, -34, 122, -15, 33, -133),
														GEO_OPEN_NODE(),
															GEO_ASM(1, Geo18_80277824),
															GEO_ROTATION_NODE(0, 0, 0, 0),
															GEO_OPEN_NODE(),
																GEO_DISPLAY_LIST(4, _000_displaylist_002_mesh),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
												GEO_DISPLAY_LIST(1, _000_offset_003_skinned),
												GEO_TRANSLATE_ROTATE(1, 96, -28, 77, 0, 0, -5),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
													GEO_OPEN_NODE(),
														GEO_TRANSLATE_ROTATE(1, 0, 0, 0, 0, 0, 5),
														GEO_OPEN_NODE(),
															GEO_ANIMATED_PART(1, 0, 0, 0, _000_offset_003_mesh),
															GEO_OPEN_NODE(),
																GEO_DISPLAY_LIST(1, _000_offset_004_skinned),
																GEO_ANIMATED_PART(1, 121, -11, 0, _000_offset_004_mesh),
																GEO_OPEN_NODE(),
																	GEO_SWITCH_CASE(1, geo_switch_mario_hand),
																	GEO_OPEN_NODE(),
																		GEO_NODE_START(),
																		GEO_OPEN_NODE(),
																			GEO_ANIMATED_PART(1, 113, 0, 0, NULL),
																			GEO_OPEN_NODE(),
																				GEO_ASM(1, Geo18_802775CC),
																				GEO_SCALE(0, 65536),
																				GEO_OPEN_NODE(),
																					GEO_DISPLAY_LIST(1, _000_displaylist_003_mesh),
																				GEO_CLOSE_NODE(),
																			GEO_CLOSE_NODE(),
																		GEO_CLOSE_NODE(),
																		GEO_BRANCH(1, right_hand_open_armature),
																	GEO_CLOSE_NODE(),
																GEO_CLOSE_NODE(),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
												GEO_DISPLAY_LIST(1, _000_offset_006_skinned),
												GEO_ANIMATED_PART(1, 95, -28, -77, NULL),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(1, 0, 0, 0, _000_offset_006_mesh),
													GEO_OPEN_NODE(),
														GEO_DISPLAY_LIST(1, _000_offset_007_skinned),
														GEO_TRANSLATE_ROTATE(1, 115, -11, 0, 0, 0, 0),
														GEO_OPEN_NODE(),
															GEO_ANIMATED_PART(1, 0, 0, 0, _000_offset_007_mesh),
															GEO_OPEN_NODE(),
																GEO_SWITCH_CASE(0, geo_switch_mario_hand),
																GEO_OPEN_NODE(),
																	GEO_NODE_START(),
																	GEO_OPEN_NODE(),
																		GEO_ANIMATED_PART(1, 121, 0, 0, NULL),
																		GEO_OPEN_NODE(),
																			GEO_ASM(0, Geo18_802775CC),
																			GEO_SCALE(0, 65536),
																			GEO_OPEN_NODE(),
																				GEO_DISPLAY_LIST(1, _000_displaylist_004_mesh),
																			GEO_CLOSE_NODE(),
																			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
																		GEO_CLOSE_NODE(),
																	GEO_CLOSE_NODE(),
																	GEO_BRANCH(1, left_hand_open_armature),
																	GEO_BRANCH(1, left_hand_peace_armature),
																	GEO_BRANCH(1, left_hand_cap_armature),
																	GEO_BRANCH(1, left_hand_wing_cap_armature),
																GEO_CLOSE_NODE(),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_DISPLAY_LIST(1, _000_offset_009_skinned),
										GEO_ANIMATED_PART(1, -83, 11, 41, NULL),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(1, 0, 0, 0, _000_offset_009_mesh),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(1, _000_offset_010_skinned),
												GEO_ANIMATED_PART(1, 196, -17, -6, _000_offset_010_mesh),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(1, _000_offset_011_skinned),
													GEO_ANIMATED_PART(1, 228, 36, 0, _000_offset_011_mesh),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_DISPLAY_LIST(1, _000_offset_012_skinned),
										GEO_ANIMATED_PART(1, -83, 11, -41, NULL),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(1, 0, 0, 0, _000_offset_012_mesh),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(1, _000_offset_013_skinned),
												GEO_ANIMATED_PART(1, 196, -17, 9, _000_offset_013_mesh),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(1, _000_displaylist_005_skinned),
													GEO_ANIMATED_PART(1, 228, 36, -15, NULL),
													GEO_OPEN_NODE(),
														GEO_ASM(2, Geo18_802775CC),
														GEO_SCALE(0, 65536),
														GEO_OPEN_NODE(),
															GEO_DISPLAY_LIST(1, _000_displaylist_005_mesh),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_BRANCH(1, _002_switch_opt0_001_switch_opt1),
							GEO_BRANCH(1, _002_switch_opt0_001_switch_opt2),
							GEO_BRANCH(1, _002_switch_opt0_001_switch_opt3),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ASM(1, geo_mirror_mario_backface_culling),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(0, material_revert_render_settings),
		GEO_DISPLAY_LIST(1, material_revert_render_settings),
		GEO_DISPLAY_LIST(2, material_revert_render_settings),
		GEO_DISPLAY_LIST(3, material_revert_render_settings),
		GEO_DISPLAY_LIST(4, material_revert_render_settings),
		GEO_DISPLAY_LIST(5, material_revert_render_settings),
		GEO_DISPLAY_LIST(6, material_revert_render_settings),
		GEO_DISPLAY_LIST(7, material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
